name: Publish Python Package

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Adjust this version as needed.

      - name: Get the previous commit
        id: prev-commit
        run: echo "::set-output name=commit::$(git rev-parse HEAD^1)"

      - name: Compare pyproject.toml version
        id: version-check
        run: |
          PREV_VERSION=$(git show ${{ steps.prev-commit.outputs.commit }}:pyproject.toml | grep '^version = ' | sed 's/version = //g')
          CURR_VERSION=$(grep '^version = ' pyproject.toml | sed 's/version = //g')
          echo "PREV_VERSION=$PREV_VERSION"
          echo "CURR_VERSION=$CURR_VERSION"
          if [ "$PREV_VERSION" != "$CURR_VERSION" ]; then
            echo "::set-output name=version_changed::true"
          else
            echo "::set-output name=version_changed::false"
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install project dependencies and build
        run: |
          poetry install

      - name: Publish to PyPI
        if: steps.version-check.outputs.version_changed == 'true'
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --build --username __token__ --password $POETRY_PYPI_TOKEN_PYPI